version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: postgres
    depends_on:
      - postgres
    volumes:
      - metabase_data:/metabase-data

  postgres:
    image: postgres:latest
    container_name: postgres_metabase
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: metabaseappdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  metabase_data:
    driver: local
  postgres_data:
    driver: local
